# -*- coding: utf-8 -*-
"""Artigo TTD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUerhpbi15n2cPvNht6hy053reFQVJ28

Importações de Bibliotecas
"""

from sklearn.preprocessing import LabelEncoder
import pandas as pd

"""Pré-Tratamento os dados (conversão de respostas em texto para valores numéricos"""

def create_csv(path, name):

  df = pd.read_csv(path, sep=';')

  # Create a LabelEncoder instance
  label_encoder = LabelEncoder()

  df['funcao']= label_encoder.fit_transform(df['funcao'])
  df['idade_range']= label_encoder.fit_transform(df['idade_range'])
  df['genero']= label_encoder.fit_transform(df['genero'])
  df['nivel_academico']= label_encoder.fit_transform(df['nivel_academico'])
  df['campo_estudo']= label_encoder.fit_transform(df['campo_estudo'])
  df['paises']= label_encoder.fit_transform(df['paises'])

  csv_name = name + ".csv"

  # Save the updated DataFrame to a new CSV
  df.to_csv(csv_name, index=False)

  return df

data = create_csv(path="./drive/MyDrive/Colab_Data/Pesquisa TTD.csv", name="data")